chore: move s3 content to lib
canonical/vault-k8s-operator pull request #304
Opened 2024-04-14 14:04 UTC by gruyaume

# Description

We move the s3 content to a charm library instead of a local helper.

## Rationale

This code will be shared by both the k8s and machine charms 

## Notes
As a follow-up PR we will want to fetch this lib in the machine charm.

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-04-18 10:01 UTC, saltiyazan requested changes
Beautiful, I added a few minor comments.
One general suggestion I have, and we can include it in this PR or not is to move these two S3 related functions from the charm file to the lib:
`_get_missing_s3_parameters`
`_get_s3_parameters`

I don't think we are using or doing anything strictly related to the charm here.

2024-04-18 10:55 UTC, gruyaume commented
> Beautiful, I added a few minor comments. One general suggestion I have, and we can include it in this PR or not is to move these two S3 related functions from the charm file to the lib: `_get_missing_s3_parameters` `_get_s3_parameters`
> 
> I don't think we are using or doing anything strictly related to the charm here.

I would leave those out as they interact with the relation data (through `s3_requirer`) and are not pure s3 calls.

2024-04-18 11:19 UTC, gruyaume commented on tests/unit/lib/charms/vault_k8s/v0/test_vault_s3.py
Done

2024-04-18 11:19 UTC, gruyaume commented on src/charm.py
Done

2024-04-18 14:15 UTC, saltiyazan approved these changes

2024-04-18 16:25 UTC, gruyaume commented on src/charm.py
> +            event.fail(message=f"S3 pre-requisites not met. {s3_pre_requisites_err}.")
Indeed, I couldn't find a better way to do this

2024-04-18 16:27 UTC, gruyaume commented on lib/charms/vault_k8s/v0/vault_s3.py
> +        except BotoCoreError:
done

2024-04-19 06:00 UTC, Kayra1 approved these changes

2024-04-19 06:01 UTC, Kayra1 commented on src/charm.py
> +            event.fail(message=f"S3 pre-requisites not met. {s3_pre_requisites_err}.")
its the best way

2024-04-19 09:35 UTC, merged