fix: multiple kv requirers
canonical/vault-k8s-operator pull request #442
Opened 2024-07-23 12:02 UTC by kayra1

# Description

Currently, we use `get_relation` to get the KV requirers. This is raising a TooManyRelatedApps error. We should use something else.

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-07-24 12:57 UTC, gruyaume requested changes

2024-07-24 13:09 UTC, kayra1 commented on tests/integration/test_integration.py
most likely yes. I will do it once i get the chance.

2024-07-24 13:11 UTC, kayra1 commented on tests/integration/test_integration.py
we actually _almost_ test this [here](https://github.com/canonical/vault-k8s-operator/blob/d01fb203af9a2530e352520a29b912db5dc0179c/tests/unit/lib/charms/vault_k8s/v0/test_vault_kv.py#L242).

2024-07-24 13:37 UTC, kayra1 commented on tests/integration/test_integration.py
added

2024-07-25 14:24 UTC, gruyaume approved these changes

2024-07-26 09:35 UTC, merged