refactor: replace tls lib v3 with v4 for access
canonical/vault-k8s-operator pull request #463
Opened 2024-08-20 21:25 UTC by gruyaume

# Description

Replace the TLS certificates library V3 with V4 for the access integration. 

## Use of self-signed certificates
The Vault charm can effectively operate in two modes for its own tls certificates:
- Self Signed
- TLS integration

Here we explicitly state those two modes. When we use self signed we generate our own certs and when we use the tls integration, we ask certs using the integration.

## This change does not include the PKI integration
In order to make this change a bit smaller we only include here the Access integration. A separate PR will focus on the PKI integration.

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-08-22 19:59 UTC, ghislainbourgeois requested changes
Looks good, just 2 small commented out sections I think you forgot.

2024-08-22 19:59 UTC, ghislainbourgeois commented on lib/charms/vault_k8s/v0/vault_tls.py
> +    #     self.charm.on.config_changed.emit()
Is this still needed?

2024-08-22 19:59 UTC, ghislainbourgeois commented on lib/charms/vault_k8s/v0/vault_tls.py
> +    #     logger.debug("Removed existing certificate files from workload.")
Is this still required?

2024-08-22 21:15 UTC, gruyaume commented on lib/charms/vault_k8s/v0/vault_tls.py
> +    #     self.charm.on.config_changed.emit()
Oops I should have delete this. Done.

2024-08-22 21:16 UTC, gruyaume commented on lib/charms/vault_k8s/v0/vault_tls.py
> +    #     logger.debug("Removed existing certificate files from workload.")
Oops I should have delete this. Done.

2024-08-23 11:29 UTC, kayra1 commented
@saltiyazan this is the same issue you were having with the integration tests. How did you resolve it?

2024-08-23 18:35 UTC, ghislainbourgeois approved these changes

2024-08-23 19:54 UTC, merged