Add provider side of certificate transfer interface
canonical/vault-k8s-operator pull request #53
Opened 2023-10-03 14:44 UTC by gatici

# Description

- Send CA certificate by adding certificate transfer interface which is necessary to integrate with Traefik which requires knowing about Vault’s CA certificate.
- Enable metallb for integration tests. Traefik requires metallb and certifacate_transfer interface relation is tested with Traefik.

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that validate the behaviour of the software
- [x] I validated that new and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-10-06 12:59 UTC, ghislainbourgeois requested changes

2023-10-11 08:32 UTC, gatici commented on README.md
> +Traefik requires to know about Vault’s CA certificate and the certificate-transfer is used to send VAult's CA certificate in the relation databag.
Done

2023-10-11 09:21 UTC, gatici commented on .github/workflows/integration-test.yaml
> +        default: "10.0.0.2-10.0.0.10"
:)

2023-10-11 09:21 UTC, gatici commented on src/charm.py
> +                    send_ca_cert.set_certificate("", ca, [], relation_id=relation.id)
Added. Done

2023-10-11 09:21 UTC, gatici commented on src/charm.py
> +                send_ca_cert.set_certificate("", ca, [], relation_id=rel_id)
Done

2023-10-11 11:49 UTC, patriciareinoso approved these changes

2023-10-11 13:46 UTC, ghislainbourgeois approved these changes

2023-10-11 13:57 UTC, merged