feat: Add loki log forwarding
canonical/vault-k8s-operator pull request #77
Opened 2023-11-22 08:39 UTC by Kayra1

# Description
**What?**

This change adds automatic log forwarding to Vault when integrated with loki.

**Why?**

This will allow users to see their 

**Where?**

This change can be used by all deployments of the vault-k8s charm.

**How?**

On receiving a loki-push-api integration, a pebble layer including `log-forwarding` with the given URL is created and placed in the plan, and the vault container is restarted to include it. On relation departure, this plan is removed and the container restarted again.

**When?**

This change will be released on the next version of the library, revision 51.

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-22 08:40 UTC, Kayra1 commented
I used to use this format for my PR's, I wanted to test it out to see what you guys think also.

2024-02-28 16:44 UTC, gruyaume requested changes

2024-02-28 16:44 UTC, gruyaume commented on lib/charms/loki_k8s/v0/loki_push_api.py
Let's use `v1` of the lib. It comes with the LogForwarder class making it so that we don't even have to manually interface with pebble's log-targets. 

See this PR for example:
- https://github.com/canonical/sdcore-amf-k8s-operator/pull/96/

2024-02-29 09:47 UTC, Kayra1 commented on lib/charms/loki_k8s/v0/loki_push_api.py
Nice. Done.

2024-02-29 14:11 UTC, merged