Uses the tls-certificates interface v1
canonical/vault-k8s-operator pull request #8
Opened 2022-08-19 20:59 UTC by gruyaume

# Description

Uses the tls-certificates interface v1 (CSR's are now passed in relation data instead of certificates)

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-08-24 17:44 UTC, ghislainbourgeois approved these changes

2022-08-29 11:24 UTC, sanchezfdezjavier requested changes

2022-08-29 11:24 UTC, sanchezfdezjavier commented on tests/unit/certificates.py
> +        sans (list): List of subject alternative names
```suggestion
        private_key_password (bytes): Private key password.
        sans (list): List of subject alternative names.
```

2022-09-07 07:27 UTC, sanchezfdezjavier approved these changes

2022-09-07 13:30 UTC, merged